# Generated by Django 5.0.1 on 2024-01-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='place',
            new_name='price',
        ),
    ]
